openapi: 3.0.0
info: 
  title: "Kebudayaan Indonesia API"
  version: "1.0.0"
  description: "API untuk Kebudayaan Indonesia"
  components:
    securitySchemes:
      bearerAuth: 
        type: http
        scheme: bearer
        bearerFormat: JWT
  security:
    bearerAuth: []

servers: 
  - url: http://localhost:8080/api/v1

tags:
  - name: Auth
    description: 'Authentication endpoints'
  - name: Admin
    description: 'Admin side'
  - name: Budaya

paths: 
  /login: 
    post:
      summary: Login as admin
      tags: [Auth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - password
              properties:
                username:
                  type: string
                  example: admin
                password: 
                  type: string
                  format: password
      responses:
        '200':
          description: A successful response login
        '400':
          description: A failed response login
  /logout:
    post:
      summary: Logout as Admin
      tags: [Auth]
      responses:
        '200':
          description: Successful logout
        '400': 
          description: Already logged out
  /admin:
    get:
      summary: Get Active Admin
      tags: [Admin]
      responses:
        '200':
          description: A list of active admin
        '400':
          description: Admin is missing
  /admin/create:
    post:
      summary: Create Admin
      tags: [Admin]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - username
                - password
              properties:
                nama_admin:
                  type: string
                  example: admin
                username:
                  type: string
                  example: admin
                password: 
                  type: string
                  format: password
                email:
                  type: string
                  example: email@mail.com
      responses:
        '201':
          description: Admin Created
        '400':
          description: Invalid payload
  /budaya:
    get:
      summary: To get all budaya as admin
      tags: [Budaya]
      responses:
        '200':
          description: Budaya is retrieved
        '401':
          description: Unauthorized

components:
  schemas: 
    Login:
      type: object
      required:
        - username
        - password
      properties:
        username:
          type: string
        password: 
          type: string
    Create Admin: 
      type: object
      properties:
        username:
          type: string
        name: 
          type: string
        password: 
          type: string
